/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by `next dev`/`next build` — do not edit.
// A minimal stub is checked in here only so the repo has one before first run.
